### ISSUE TITLE
update for 1.0

### ISSUE THREAD

**Issue by JulyMorning** [kPherox/MBSSpotlights#2]
please :3

**Comment by kphrx** [comment]
Since a similar Mod already exists, I don't think it is need to update this mod for latest version.

A similar Mod's name is "MiningCo. Projector"

Links:
- [GitHub Repository](https://github.com/Rikiki123456789/Rimworld/tree/master/MiningCo.%20Projector)
- [Steam Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=955561873)
- [Ludeon Forums](https://ludeon.com/forums/index.php?topic=14711.msg153946#msg153946)

**Comment by JulyMorning** [comment]
yeah, already found it. thanks.
